language: node_js
node_js:
- '4.4'
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
install:
- npm install
script:
- gulp release
deploy:
  provider: s3
  access_key_id: AKIAI3FXFNMM35JXIZ6A
  secret_access_key:
    secure: JTGYJ3x9KlmWPhaBjt2IqfwqOVXbw7GOXKPGuNttwc8kOntsosekkAsHhxFInN7cxf/osmf5/GIULLHX7uWUysppz6tOGnEvznkWP25V8T+rb0QenAT0XpL7Y7WnNEtCpMoXf3oU7As7tvZrzl4nDLM9Tu8UcoaKX90zZ2kQh2tgwyB3V08vZjgLB2Z1qgitEXTDhkQCwRpgHk+3P9GfESclJ0tXkshKwb5Gi62MBwf16XtF0un/zIzKfC4HwwFi0xnzb1lrzKgTrryo9VdYhUoI2Bzd9Edc7xz2I3Mgsdqa426fDU5caAvRirelTdrGS/gZfTPYRMM0Tuulo+NN31ES/RwSThaA7UeUezoix/M3CbCwaFgxPm8UQzYyV+o0xX/nVvypEwfqZDapZZpM/SG8nS+CkLlB8/T4RzGDX8tPqZ9NIG0zkJBfTxb5oaR5JpooQl5NU5nJ7OQ0Aya3KuOPEjQ43WyoT4mbwSuG5N9tp/ioG6iyhobDXZe6w504EUQex2y6mFdjh7TUz7Fc56RimE7yiS3t7HZvFTbnC8+8mp4pG8H/1oQ5j6eIV6L2QE5WS8bIr2vbHnVZ8M3j76pVSWcGETqZh5NBNeiRceVa2xfhassLE5IJ1XFNVNd2jEEoQVQZv8Y9p7muyMuXcjoW84q/1SwYSFibeNTSUrY=
  bucket: brexit.vote
  skip_cleanup: true
  region: eu-west-1
  local_dir: release
env:
  global:
    secure: K1mr4KX46R5Lv0D9F+NJ/FxKsZIu/JcpTlmSU3f011cq9tu3G22pLwGpx9V6xY28stfN/d4AGHPQFx8hcHM288axR94j5oIMRb567okaZXKI9xM6rPbmI2mzfZ7ophGJ9l/WAVKLp8hUW4vBGH4wzBRP0R8SHx206oHpLB/OYJoPL3siPD+n4wGD+Op6pk3YV4l6v4MHmGyjZjrAdgS6T17R4HjgoXvaBGHeHvgOJMOdmo7p9E7bdYWL8XPXlsGIU4L5yf/D4aaFS044FmYQUoFEx+ttPEj/FZRtIEWpRg0gefcvnq1KY9Z2O09NMz7+Fpz1dWL2rYQ4TWCX92/vmoNE6tt7u5itQvCjgZKKCF46ukA9OSPMOuf30/1y/Yc5gkc3l+Cm880riznOy3WJ5Vsg8UMDTv/T8b8rOd3JRMvOet/N0q82+Sc+HE4EvfkPCOCdGbSLX9iuFP5v+4q4DHsm8qOWF0ML+nAiIElilIPE7kIEBRlpdell4r3aI5fZHqMavuj88XNrk50YO1Ors3kKbYJrwqeOqCRKv7tY/+Ea4u5nPu93+g7cqvj2J0nq8abNbS93qXIGgUIjtbBOTmLwoEOPGyz0s3hJB/duywGfOKXJjYEuNvAZlmlYAxV7/szNgnlm1qp6UAQjKA2jPZsNeS7Cv0wCSZK1zEpoX3g=
